sudo: required
services:
  - docker

before_install:
  - docker build -t theolderbear/docker -f Dockerfile.dev .

script:
  - docker run theolderbear/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-web"
  env: "DockerReactWeb-env"
  bucket_name: "elasticbeanstalk-eu-central-1-374825790429"
  bucket_path: "docker-react-web"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"